version: "3.4"

services:
  working:
    build: .
    image: yop-decider
    container_name: yop-decider
    ports:
      - 5001:5001
    volumes:
      - ../package.json:/home/node/package.json
      - ../package-lock.json:/home/node/package-lock.json
      - ../.nvmrc:/home/node/.nvmrc
      - ../.prettierignore:/home/node/.prettierignore
      - ../domain:/home/node/domain
      - ../app:/home/node/app
      - ../yop:/home/node/yop
      - ../events.json:/home/node/events.json
