name: CI

on: push

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: Run tests
        run: npm run ci
