name: Tests

on: push

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: checkout submodule yop
        run: |
          git submodule update --init --recursive
      - name: Run tests
        run: npm run ci
